[build]
  command = "npm run build"
  publish = "out"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/deals"
  to = "/.netlify/functions/deals-redirect"
  status = 200
  force = true
